### ISSUE TITLE
haproxy_all.cfg is missing Heat config

### ISSUE THREAD

**Issue by fghaas** [hastexo/academy-ansible#1]
https://github.com/hastexo/academy-ansible/blob/c5834156bfea65d35d5acd0023bdc8d3273ec666/roles/ubuntu.controller/files/haproxy_all.cfg

Heat frontends and backends are missing, meaning we are unable to use Heat even though it's being properly deployed.

**Comment by arbrandes** [comment]
ACK, I'll bake those in.
